### ISSUE TITLE
Adobe Reader não abre danfe.

### ISSUE THREAD

**Issue by olivermathe** [brasil-js/danfe#2]
![capturar](https://cloud.githubusercontent.com/assets/12900166/19004030/11f9e084-872a-11e6-925a-0cbfd0e0a69a.PNG)

Estava tendo este erro ao tentar abrir o arquivo no Adobe Reader (Versão 11.0.17), acabei descobrindo que o error era referente as linhas.

Na geração das linhas o método "stroke()" recebe parâmetros, por alguma razão o Adobe não estava intendo-as, também removi o método "dash()" de linhas onde ele não era necessário (linhas não tracejadas).

Como estava:
`return pdf.moveTo(x1, y).lineTo(x2, y).dash(false).stroke(cor || args.corDoLayout);`
Como ficou:
`return pdf.moveTo(x1, y).lineTo(x2, y).stroke();`

Após alteração não tive mais problemas.

**Comment by renatoargh** [comment]
@olivermathe obrigado pela observação e por usar o módulo. Teria como enviar um pull request? Valeu
