### ISSUE TITLE
Download no navegador

### ISSUE THREAD

**Issue by paulowolking** [brasil-js/danfe#4]
Olá, como eu poderia integrar esse script a ser executado em uma ação no meu site e fazer download no navegador?

**Comment by veronesecoms** [comment]
Olá, conseguiu resolver?

**Comment by diegofullstackjs** [comment]
Imagino que você deve gerar a nota e fazer que browser se redirecione onde este encontrado esse danfe gerador o navegador automaticamente vai pedir pra salvar o arquivo
